### ISSUE TITLE
【TOT】神州重工武器包 Support

### ISSUE THREAD

**Issue by FicusC** [Epicguru/AnimationMod#16]
Hello author, I am communicating with you through translation software, please forgive me if there is any inappropriate wording.
Can this melee weapon support called "【TOT】神州重工武器包" be added? Thanks!
[https://steamcommunity.com/sharedfiles/filedetails/?id=2883670795&searchtext=TOT](url)

**Comment by Epicguru** [comment]
Added support in latest version.
