### ISSUE TITLE
Mod Support Request

### ISSUE THREAD

**Issue by WynishKnight** [Epicguru/AnimationMod#19]
May I request support for the following mods, my glorious guru? <3

https://steamcommunity.com/sharedfiles/filedetails/?id=2878807817&searchtext=edo+themed

https://steamcommunity.com/sharedfiles/filedetails/?id=2899078092

https://steamcommunity.com/sharedfiles/filedetails/?id=2880558608&searchtext=medieval+times

https://steamcommunity.com/sharedfiles/filedetails/?id=2905623211&searchtext=Elves

https://steamcommunity.com/sharedfiles/filedetails/?id=2839780788&searchtext=Motz

https://steamcommunity.com/sharedfiles/filedetails/?id=2884249920&searchtext=malay

**Comment by Epicguru** [comment]
Edo Themed Expansion: already supported.
Elves: already supported.
Support for the others has now been added.
