### ISSUE TITLE
Mod Support Request

### ISSUE THREAD

**Issue by Transflux24** [Epicguru/AnimationMod#21]
I was hoping to get a couple of mods patched for a western themed setup I'm working on, the weapons needing patches is only a couple per mod. Quite a bit of overlap between the mods but I'm not sure what ones be using to unify across the pack, and I'm sure not everyone will use all 3 together only. Thanks.

**_Westerado (Continued):_**
**Link:** https://steamcommunity.com/sharedfiles/filedetails/?id=2236973780
**Weapons Need Patching:**
-Bowie Knife
-Tomahawk
-Cavalry Saber

_**Rimworld Westernization Project**_
**Link:** https://steamcommunity.com/sharedfiles/filedetails/?id=2237100861

**Weapons Need Patching:**
-Bowie Knife
-Model 1840 Heavy Cavalry Saber
-Model 1860 Light Cavalry Saber
(There's Bayonet versions of firearms, but I'm not really sure it's necessary to patch these, I think vanilla animations will be fine)

_**Vanilla Factions Expanded - Settlers**_
**Link:** https://steamcommunity.com/workshop/filedetails/?id=2052918119

**Weapons Need Patching:**
-Tomahawk

**Comment by Epicguru** [comment]
Support has been added. Thanks for the well formatted request.

**Comment by Transflux24** [comment]
Really appreciate the work.
