### ISSUE TITLE
Mod support request

### ISSUE THREAD

**Issue by Greywolfgames** [Epicguru/AnimationMod#22]
hello! i love the mod and the work youve put in, i was wondering if i could request a patch for the outer rim series please

mando
https://steamcommunity.com/sharedfiles/filedetails/?id=2920516629&searchtext=

core
https://steamcommunity.com/sharedfiles/filedetails/?id=2919227155&searchtext=

those look like the only ones with CQC weapons, again thank you for all your hard work!

**Comment by Epicguru** [comment]
Added support.

**Comment by Greywolfgames** [comment]
thank you so much
