### ISSUE TITLE
Support for Warcaskets: Adeptus Astartes

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [Epicguru/AnimationMod#29]
Hi,

I was intending to make a playlist with a theme of neolithic to SoS / Warhammer 40k as such I was planning on using this mod for the endgame alongside SoS since it supports it.

I hope you have some spare time to patch it in as it would be greatly appreciated!

You can find the mod here: [Warcaskets: Adeptus Astartes](https://steamcommunity.com/sharedfiles/filedetails/?id=2816582751&searchtext=)

**Comment by Epicguru** [comment]
Added support in latest update.
