### ISSUE TITLE
Support for Roo's Minotaur Xenotype Expanded

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [Epicguru/AnimationMod#30]
Hi,

I saw you support the Roo's Minotaur Xenotype mod, but not it's extension, which also adds 2 melee weapons.

I hope you have some spare time to patch it in as it would be greatly appreciated!

You can find the mod here: [Roo's Minotaur Xenotype Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2927815286)

**Comment by Epicguru** [comment]
Added support now.
