### ISSUE TITLE
Support for Impact Weaponry 

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [Epicguru/AnimationMod#31]
Hi,

I saw you support DetVisor's Glitter Weaponry, but His other mod, which also adds melee weapons.

I hope you have some spare time to patch it in as it would be greatly appreciated!

You can find the mod here: [Impact Weaponry](https://steamcommunity.com/sharedfiles/filedetails/?id=2965398269&searchtext=Athena)

**Comment by Epicguru** [comment]
Added support in latest update
