### ISSUE TITLE
Support for Roo's Satyr and Faun Xenotypes

### ISSUE THREAD

**Issue by boniblade** [Epicguru/AnimationMod#32]
Don't know if Faun has weapons, but these two do!

[Roo's Satyr Xenotype](https://steamcommunity.com/sharedfiles/filedetails/?id=2971803439)

[Roo's Satyr and Faun Xenotypes Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2971804169)

**Comment by Epicguru** [comment]
These mods are already supported.
