### ISSUE TITLE
Support for Elden Rim: Armory

### ISSUE THREAD

**Issue by Zencal** [Epicguru/AnimationMod#36]
Hi,

It'd be appreciated if support could be added for [Elden Rim: Armory](https://steamcommunity.com/sharedfiles/filedetails/?id=2981408637&searchtext=Elden+Ring), there are roughly 13 weapons at the moment with more on the way. It does make use of [Enable Oversized Weapons](https://steamcommunity.com/workshop/filedetails/?id=2543371889) to do it's own hand positioning by the looks of things, I'm not sure if that would be a problem

Great work so far, the animations bring so much life to the game

Thanks

**Comment by Epicguru** [comment]
Added in latest release.
